spring:
  application:
    name: incedents
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1111
    url: jdbc:postgresql://localhost:5432/incidents
